# .goreleaser.yml
# Build customization
builds:
  - binary: config-bob
    main:   main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

# .goreleaser.yml
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

# Publish to homebrew
brews:
  # Reporitory to push the tap to.
  - tap:
      owner: foomo
      name: homebrew-config-bob

    caveats: "config-bob -h"
    homepage: "https://github.com/foomo/config-bob"
    description: "CLI utility to generate secure configurations"