# Check out the README.md file in the root project to see how to configure
export OP_LOCAL_ACCOUNT=my-op-account@company.com
export OP_VAULT=my-super-cool-uuid

build:
	config-bob build -t templates -o output