---
killer: {{ yaml .yamlKiller }}
foo: {{.Foo.Secret}}
account:
  name: {{ secret "secret/smtp.name" }}
  password: {{ secret "secret/smtp.password" }}
payment:
  token: {{ secret "secret/payment.token" }}
