# Check out the README.md file in the root project to see how to configure
export GCP_APPLICATION_CREDENTIALS=my-gcp-project-credentials.json
export GCP_PROJECT=my-gcp-project

build:
	config-bob build -t templates -o output